FizzBuzz
isshi-hasegawa/ruby-practices pull request #1
Opened 2021-05-17 09:08 UTC by isshi-hasegawa

2021-05-20 06:39 UTC, komagata commented
コミットはくっつけたり、消したり分割したり自由にできるので理想の状態になるように修正してみてください〜

2021-05-22 15:14 UTC, isshi-hasegawa commented
ありがとうございます！
おまたせしましたが、コミットをまとめましたので再度ご確認お願い致します〜

2021-05-23 04:02 UTC, komagata requested changes

2021-05-23 04:02 UTC, komagata commented on 01.fizzbuzz/fizz_buzz.rb
> +[*1..20].each do |n|
```suggestion
(1..20).each do |n|
```

間違いではないですが、RangeをArrayに変換する意味はないのでこれでいいかもです。

2021-05-23 05:06 UTC, isshi-hasegawa commented on 01.fizzbuzz/fizz_buzz.rb
> +[*1..20].each do |n|
言われてみれば…仰るとおりです！
`1..20`を()でひとつの式にグループ化してあげればよいだけで、わざわざArrayに変換する必要はありませんでした。
Commit chagesで変更をコミットしました〜！

2021-05-24 03:23 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-24 03:53 UTC, isshi-hasegawa commented
ご確認ありがとうございます！

2021-05-24 03:53 UTC, merged